<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>E003LinuxHostControls</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Configuration>ExportRelease</Configuration>
    <GodotTargetPlatform>linuxbsd</GodotTargetPlatform>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <RuntimeFrameworkVersion>9.0.7</RuntimeFrameworkVersion>
    <PublishTrimmed>false</PublishTrimmed>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GodotDisabledSourceGenerators>GodotPluginsInitializer</GodotDisabledSourceGenerators>
  </PropertyGroup>
</Project>
